#!/bin/bash -login

##walltime-how long expected to run
#PBS -l walltime=8:00:00

#Memory needed
#PBS -l mem=30gb

#PBS -l feature="intel16" nodes=2:ppn=32

#output and error files name
#PBS -j oe

# Send me and email incase something happens
#PBS -m abe

#PBS -M shinjasm@msu.edu

#Name of Job
#PBS -N taylor-green4

module load OpenMPI/1.4.4 
module load powertools

cd /mnt/scratch/shinjasm/newrun3/

./lazy.sh 
 






